apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fiap-classe
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: fiap-pv
  namespace: fiap-soat11
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: fiap-classe
  hostPath:
    path: /mnt/data