apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fiap-pvc
  namespace: fiap-soat11
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: fiap-classe