apiVersion: v1
kind: Secret
metadata:
  name: fiap-mysql-secrets
  namespace: fiap-soat11
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: ZmlhcC1zb2F0MTFAcGFzcw==
  MYSQL_DATABASE: ZmlhcA==
  MYSQL_USER: dXNlcl9maWFw
  MYSQL_PASSWORD: cGFzc19maWFw