name: Criar S3 Bucket
on:
    workflow_dispatch:
jobs:
    create-s3-bucket:
        runs-on: ubuntu-latest
        steps:
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
                aws-region: ${{ vars.AWS_REGION }}

            - name: Create S3 bucket
              run: |
                aws s3api create-bucket --bucket "s3-fiap-soat" --region ${{ vars.AWS_REGION }}