name: Criar recursos no EKS
on:
    workflow_dispatch:
jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ID }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ vars.AWS_REGION }}      
      - name: Carregar Kube Config
        run: |
          aws eks update-kubeconfig \
          --name ${{ vars.CLUSTER_NAME }} \
          --region ${{ vars.AWS_REGION }}      
      - name: Aplicar Configurações no EKS
        run: |
          kubectl apply -f k8s/eks-deployment.yaml
          kubectl apply -f k8s/eks-svc.yaml