name: Terraform AWS
on:
    workflow_dispatch:
jobs:
    Lambda_and_EKS:
      runs-on: ubuntu-latest
      steps:
          - name: Baixando arquivos do repo
            uses: actions/checkout@v4
          - name: Aws Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
              aws-region: ${{ vars.AWS_REGION }}  
          - name: Credentials
            run: aws sts get-caller-identity
          - name: Configurando Terraform
            uses: hashicorp/setup-terraform@v3
          - name: Terraform Init
            run: terraform init -input=false
          - name: Terraform Format
            run: terraform fmt -check
          - name: Terraform Validate
            run: terraform validate
          #- name: Terraform Plan
          #  run: terraform plan -target=module.lambda -target=module.eks -out=tfplan
          - name: Terraform Apply Lambda              
            run: terraform apply -target=module.lambda -input=false -auto-approve
          - name: Terraform Apply EKS              
            run: terraform apply -target=module.eks -input=false -auto-approve
    K8S_Deploy:
      needs: Lambda_and_EKS
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Tokenizar artefatos
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '__'
            tokenSuffix: '__'
            files: './k8s/manifests/*.yml'    
          env:
            AWS_IMAGE_CONTAINER: ${{ vars.AWS_IMAGE_CONTAINER }}
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
            aws-region: ${{ vars.AWS_REGION }}  
        - name: Carregar Kube Config
          run: |
            aws eks update-kubeconfig \
            --name ${{ vars.CLUSTER_NAME }} \
            --region ${{ vars.AWS_REGION }}      
        - name: Aplicar Configurações no EKS
          run: kubectl apply -f ./k8s/manifests
        - name: Get Service LB
          run: |
            LB=$(kubectl get svc meu-service -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
            echo "SERVICE_LB=$LB" >> $GITHUB_ENV
        - name: Configurando Terraform
          uses: hashicorp/setup-terraform@v3          
        - name: Terraform Update API Gateway
          run: |
            terraform apply -var="dns_eks=${{ env.SERVICE_LB }}" -auto-approve
    Api_Gateway:
      needs: [Lambda_and_EKS, K8S_Deploy]
      runs-on: ubuntu-latest
      steps:
          - name: Baixando arquivos do repo
            uses: actions/checkout@v4
          - name: Configurando Terraform
            uses: hashicorp/setup-terraform@v3
          - name: Aws Credentials
            uses: aws-actions/configure-aws-credentials@v4
            with:
              aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
              aws-region: ${{ vars.AWS_REGION }}  
          - name: Terraform Init
            run: terraform init
          - name: Terraform Format
            run: terraform fmt -check
          - name: Terraform Validate
            run: terraform validate
          - name: Terraform Plan
            run: terraform plan -target=module.api_gateway -out=tfplan
          - name: Terraform Apply
            run: terraform apply -target=module.api_gateway -auto-approve tfplan